In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('insulin_infusion_pump_death.csv')

In [3]:
df.head()

,manufacturer_contact_zip_ext,manufacturer_g1_address_2,manufacturer_link_flag,event_type,manufacturer_contact_pcity,report_number,type_of_report,date_received,manufacturer_address_2,date_of_event,...,manufacturer_name,remedial_action,report_source_code,manufacturer_g1_zip_code,adverse_event_flag,mdr_text,distributor_name,manufacturer_g1_address_1,distributor_zip_code,manufacturer_contact_postal_code
0,1219,NaN,Y,Death,81857643,2032227-2010-80235,Initial submission,20100204,NaN,20091015.0,...,NaN,NaN,Manufacturer report,91325,Y,"{mdr_text_key=21989596, text_type_code=Additio...",NaN,18000 DEVONSHIRE ST.,NaN,913251219
1,1219,ROAD 31 KM 24.4,Y,Death,81857643,3004209178-2013-90526,Initial submission,20130123,NaN,20120822.0,...,NaN,NaN,Manufacturer report,00777,Y,"{mdr_text_key=3151704, text_type_code=Descript...",NaN,CEIBA NORTE IND. PARK #50,NaN,913251219
2,3428,NaN,Y,Death,40895647,2531779-2011-04263,Initial submission,20110618,NaN,20110428.0,...,NaN,NaN,Manufacturer report,19380,Y,"{mdr_text_key=18178260, text_type_code=Descrip...",NaN,200 LAWRENCE DR,NaN,193803428
3,1219,CEIBA NORTE INDUSTRIAL PARK,Y,Death,81857643,3004209178-2010-80078,Initial submission,20100119,NaN,20090425.0,...,NaN,NaN,Manufacturer report,00777,Y,"{mdr_text_key=21829400, text_type_code=Additio...",NaN,"CALL BOX 4070, RD31, KM24, HM4",NaN,913251219
4,1219,NaN,Y,Death,81857643,2032227-2013-03519,Initial submission,20130810,NaN,20080901.0,...,NaN,NaN,Manufacturer report,91325,Y,"{mdr_text_key=3756111, text_type_code=Descript...",NaN,18000 DEVONSHIRE STREET,NaN,913251219

In [4]:
df.columns

Index(['manufacturer_contact_zip_ext', 'manufacturer_g1_address_2',
       'manufacturer_link_flag', 'event_type', 'manufacturer_contact_pcity',
       'report_number', 'type_of_report', 'date_received',
       'manufacturer_address_2', 'date_of_event', 'manufacturer_address_1',
       'exemption_number', 'manufacturer_contact_zip_code',
       'manufacturer_contact_plocal', 'manufacturer_contact_l_name',
       'source_type', 'distributor_zip_code_ext', 'manufacturer_g1_state',
       'reporter_country_code', 'date_added', 'device_date_of_manufacturer',
       'previous_use_code', 'device', 'product_problems',
       'manufacturer_contact_country', 'manufacturer_g1_zip_code_ext',
       'date_report', 'distributor_state', 'manufacturer_g1_country',
       'manufacturer_contact_city', 'mdr_report_key',
       'removal_correction_number', 'date_manufacturer_received',
       'manufacturer_zip_code_ext', 'report_to_manufacturer',
       'manufacturer_g1_name', 'distributor_address_1', 'manufacturer_state',
       'distributor_address_2', 'manufacturer_postal_code',
       'manufacturer_country', 'single_use_flag', 'number_patients_in_event',
       'manufacturer_contact_exchange', 'manufacturer_contact_pcountry',
       'event_location', 'report_to_fda', 'manufacturer_contact_state',
       'manufacturer_contact_t_name', 'manufacturer_contact_address_2',
       'manufacturer_g1_city', 'manufacturer_contact_address_1',
       'product_problem_flag', 'pma_pmn_number', 'reprocessed_and_reused_flag',
       'report_date', 'reporter_occupation_code', 'noe_summarized',
       'manufacturer_g1_postal_code', 'date_facility_aware',
       'manufacturer_contact_area_code', 'manufacturer_contact_f_name',
       'manufacturer_zip_code', 'date_changed', 'health_professional',
       'summary_report_flag', 'manufacturer_city',
       'manufacturer_contact_extension', 'manufacturer_contact_phone_number',
       'patient', 'distributor_city', 'initial_report_to_fda', 'event_key',
       'date_report_to_manufacturer', 'number_devices_in_event',
       'date_report_to_fda', 'manufacturer_name', 'remedial_action',
       'report_source_code', 'manufacturer_g1_zip_code', 'adverse_event_flag',
       'mdr_text', 'distributor_name', 'manufacturer_g1_address_1',
       'distributor_zip_code', 'manufacturer_contact_postal_code'],
      dtype='object')

In [5]:
df.describe()

,date_received,manufacturer_address_2,date_of_event,manufacturer_address_1,exemption_number,distributor_zip_code_ext,date_added,device_date_of_manufacturer,date_report,distributor_state,...,manufacturer_city,manufacturer_contact_extension,distributor_city,event_key,date_report_to_manufacturer,number_devices_in_event,date_report_to_fda,manufacturer_name,distributor_name,distributor_zip_code
count,3.094000e+03,0.0,3.001000e+03,0.0,0.0,0.0,3.094000e+03,1.323000e+03,3.063000e+03,0.0,...,0.0,16.000000,0.0,0.0,4.200000e+01,0.0,4.000000e+01,0.0,0.0,0.0
mean,2.011892e+07,NaN,2.011439e+07,NaN,NaN,NaN,2.011913e+07,2.007943e+07,2.012045e+07,NaN,...,NaN,2038.062500,NaN,NaN,2.003542e+07,NaN,2.005412e+07,NaN,NaN,NaN
std,5.169408e+04,NaN,5.068199e+04,NaN,NaN,NaN,5.156679e+04,5.726629e+04,5.150551e+04,NaN,...,NaN,3442.913698,NaN,NaN,8.848406e+04,NaN,8.887150e+04,NaN,NaN,NaN
min,1.993010e+07,NaN,1.992121e+07,NaN,NaN,NaN,1.993011e+07,1.982020e+07,1.994021e+07,NaN,...,NaN,112.000000,NaN,NaN,1.992122e+07,NaN,1.994021e+07,NaN,NaN,NaN
25%,2.009080e+07,NaN,2.008120e+07,NaN,NaN,NaN,2.009081e+07,2.005040e+07,2.009073e+07,NaN,...,NaN,112.000000,NaN,NaN,1.997047e+07,NaN,1.998524e+07,NaN,NaN,NaN
50%,2.013112e+07,NaN,2.013061e+07,NaN,NaN,NaN,2.013113e+07,2.009070e+07,2.013120e+07,NaN,...,NaN,112.000000,NaN,NaN,2.000041e+07,NaN,2.003096e+07,NaN,NaN,NaN
75%,2.016012e+07,NaN,2.015072e+07,NaN,NaN,NaN,2.016012e+07,2.012073e+07,2.016026e+07,NaN,...,NaN,2049.750000,NaN,NaN,2.013774e+07,NaN,2.014062e+07,NaN,NaN,NaN
max,2.020123e+07,NaN,2.020113e+07,NaN,NaN,NaN,2.020123e+07,2.020012e+07,2.021082e+07,NaN,...,NaN,7812.000000,NaN,NaN,2.019092e+07,NaN,2.019083e+07,NaN,NaN,NaN

In [6]:
df['mdr_text'].describe()

count                                                  3083
unique                                                 3083
top       {mdr_text_key=21989596, text_type_code=Additio...
freq                                                      1
Name: mdr_text, dtype: object

In [7]:
df[df['mdr_text'].isnull()]

,manufacturer_contact_zip_ext,manufacturer_g1_address_2,manufacturer_link_flag,event_type,manufacturer_contact_pcity,report_number,type_of_report,date_received,manufacturer_address_2,date_of_event,...,manufacturer_name,remedial_action,report_source_code,manufacturer_g1_zip_code,adverse_event_flag,mdr_text,distributor_name,manufacturer_g1_address_1,distributor_zip_code,manufacturer_contact_postal_code
864,NaN,NaN,Y,Death,26257760,2921482-2006-00789,Initial submission,20060228,NaN,20060113.0,...,NaN,NaN,Manufacturer report,95037,N,NaN,NaN,755 JARVIS DR.,NaN,53158
952,NaN,NaN,Y,Death,NaN,2016493-1997-00220,Initial submission,19971126,NaN,19971009.0,...,NaN,NaN,Manufacturer report,NaN,Y,NaN,NaN,NaN,NaN,NaN
1568,NaN,NaN,N,Death,NaN,562917,Initial submission,20031222,NaN,20031213.0,...,NaN,NaN,User Facility report,NaN,Y,NaN,NaN,NaN,NaN,NaN
1579,6132,NaN,Y,Death,84793537,2921482-2003-00656,Initial submission,20031231,NaN,20031214.0,...,NaN,NaN,Manufacturer report,95037,Y,NaN,NaN,755 JARVIS DR,NaN,600646132
1589,NaN,NaN,Y,Death,3625958,2032227-2003-01474,Initial submission,20031231,NaN,20031120.0,...,NaN,NaN,Manufacturer report,91325,Y,NaN,NaN,18000 DEVONSHIRE ST,NaN,NaN
1744,NaN,NaN,Y,Death,NaN,2016493-1998-00226,Initial submission,19981208,NaN,19981028.0,...,NaN,NaN,Manufacturer report,NaN,N,NaN,NaN,NaN,NaN,NaN
1846,1219,NaN,Y,Death,81857643,2032227-2015-05642,Initial submission,20150218,NaN,20131223.0,...,NaN,NaN,Manufacturer report,91325,Y,NaN,NaN,18000 DEVONSHIRE STREET,NaN,913251219
2424,NaN,NaN,Y,Death,NaN,2024064-1998-00062,Initial submission,19981125,NaN,19981027.0,...,NaN,Other,Manufacturer report,NaN,Y,NaN,NaN,NaN,NaN,NaN
2433,6157,NaN,Y,Death,84793505,2921482-1999-00082,Initial submission,19990521,NaN,19990413.0,...,NaN,Other,Manufacturer report,NaN,Y,NaN,NaN,*,NaN,600646157
2457,NaN,NaN,Y,Death,NaN,2021283-1997-00036,Initial submission,19970722,NaN,19970611.0,...,NaN,NaN,Manufacturer report,NaN,N,NaN,NaN,NaN,NaN,NaN
2479,NaN,NaN,Y,Death,84727046,6000001-2000-00397,Initial submission,20000719,NaN,20000529.0,...,NaN,NaN,Manufacturer report,NaN,N,NaN,NaN,*,NaN,60073

In [8]:
df[df['device'].isnull()]

Empty DataFrame
Columns: [manufacturer_contact_zip_ext, manufacturer_g1_address_2, manufacturer_link_flag, event_type, manufacturer_contact_pcity, report_number, type_of_report, date_received, manufacturer_address_2, date_of_event, manufacturer_address_1, exemption_number, manufacturer_contact_zip_code, manufacturer_contact_plocal, manufacturer_contact_l_name, source_type, distributor_zip_code_ext, manufacturer_g1_state, reporter_country_code, date_added, device_date_of_manufacturer, previous_use_code, device, product_problems, manufacturer_contact_country, manufacturer_g1_zip_code_ext, date_report, distributor_state, manufacturer_g1_country, manufacturer_contact_city, mdr_report_key, removal_correction_number, date_manufacturer_received, manufacturer_zip_code_ext, report_to_manufacturer, manufacturer_g1_name, distributor_address_1, manufacturer_state, distributor_address_2, manufacturer_postal_code, manufacturer_country, single_use_flag, number_patients_in_event, manufacturer_contact_exchange, manufacturer_contact_pcountry, event_location, report_to_fda, manufacturer_contact_state, manufacturer_contact_t_name, manufacturer_contact_address_2, manufacturer_g1_city, manufacturer_contact_address_1, product_problem_flag, pma_pmn_number, reprocessed_and_reused_flag, report_date, reporter_occupation_code, noe_summarized, manufacturer_g1_postal_code, date_facility_aware, manufacturer_contact_area_code, manufacturer_contact_f_name, manufacturer_zip_code, date_changed, health_professional, summary_report_flag, manufacturer_city, manufacturer_contact_extension, manufacturer_contact_phone_number, patient, distributor_city, initial_report_to_fda, event_key, date_report_to_manufacturer, number_devices_in_event, date_report_to_fda, manufacturer_name, remedial_action, report_source_code, manufacturer_g1_zip_code, adverse_event_flag, mdr_text, distributor_name, manufacturer_g1_address_1, distributor_zip_code, manufacturer_contact_postal_code]
Index: []

[0 rows x 86 columns]

In [9]:
df.dtypes

manufacturer_contact_zip_ext         object
manufacturer_g1_address_2            object
manufacturer_link_flag               object
event_type                           object
manufacturer_contact_pcity           object
                                     ...
mdr_text                             object
distributor_name                    float64
manufacturer_g1_address_1            object
distributor_zip_code                float64
manufacturer_contact_postal_code     object
Length: 86, dtype: object

In [10]:
df.device

0       {manufacturer_d_address_1=18000 DEVONSHIRE ST....
1       {manufacturer_d_address_1=CEIBA NORTE IND. PAR...
2       {manufacturer_d_address_1=200 LAWRENCE DR, man...
3       {manufacturer_d_address_1=CALL BOX 4070, RD31,...
4       {manufacturer_d_address_1=18000 DEVONSHIRE STR...
                              ...
3089    {manufacturer_d_address_1=CEIBA NORTE IND. PAR...
3090    {manufacturer_d_address_1=CEIBA NORTE IND. PAR...
3091    {manufacturer_d_address_1=, manufacturer_d_add...
3092    {manufacturer_d_address_1=, manufacturer_d_add...
3093    {manufacturer_d_address_1=, manufacturer_d_add...
Name: device, Length: 3094, dtype: object

In [11]:
import json
# device_parsed_df = pd.DataFrame.from_dict(df["device"].map(lambda d : json.loads(d.replace("=", ":"))).values.tolist())
first_row_device = df["device"][0]
first_row_mdr_text = df['mdr_text'][0]

In [12]:
first_row_device

'{manufacturer_d_address_1=18000 DEVONSHIRE ST., manufacturer_d_address_2=, device_event_key=, device_sequence_number=1, manufacturer_d_state=CA, manufacturer_d_zip_code=91325, manufacturer_d_city=NORTHRIDGE, lot_number=, manufacturer_d_postal_code=91325, manufacturer_d_zip_code_ext=, date_received=20100204, model_number=MMT-511LNAL, device_report_product_code=LZG, udi_public=, device_operator=LAY USER/PATIENT, device_availability=No, other_id_number=, generic_name=INFUSION PUMP, manufacturer_d_name=MEDTRONIC MINIMED, brand_name=PUMP MMT-511LNAL PRDGM INS CL EN US LN, manufacturer_d_country=US, combination_product_flag=N, openfda={device_name=Pump, Infusion, Insulin, medical_specialty_description=General Hospital, device_class=2, regulation_number=880.5725}, device_age_text=DA, udi_di=, device_evaluated_by_manufacturer=R, catalog_number=MMT-511LNAL, implant_flag=, date_removed_flag=}'

In [13]:
first_row_mdr_text

'{mdr_text_key=21989596, text_type_code=Additional Manufacturer Narrative, patient_sequence_number=1, text=CURRENTLY, IT IS UNK WHETHER OR NOT THE DEVICE MAY HAVE CAUSED OR CONTRIBUTED TO THE EVENT AS NO PRODUCT HAS BEEN RETURNED. NO CONCLUSION CAN BE DRAWN AT THIS TIME. WE THEREFORE CONSIDER THIS REPORT COMPLETE TO THE BEST OF OUR KNOWLEDGE.}'

In [14]:
type(first_row_device), type(first_row_mdr_text)

(str, str)

In [15]:
first_row_device[0], first_row_device[-1]

('{', '}')

In [131]:
# from ast import literal_eval
# literal_eval(first_row_device[1:-1].replace('=', ':'))
first_row_device.split(', ')

['{manufacturer_d_address_1=18000 DEVONSHIRE ST.',
 'manufacturer_d_address_2=',
 'device_event_key=',
 'device_sequence_number=1',
 'manufacturer_d_state=CA',
 'manufacturer_d_zip_code=91325',
 'manufacturer_d_city=NORTHRIDGE',
 'lot_number=',
 'manufacturer_d_postal_code=91325',
 'manufacturer_d_zip_code_ext=',
 'date_received=20100204',
 'model_number=MMT-511LNAL',
 'device_report_product_code=LZG',
 'udi_public=',
 'device_operator=LAY USER/PATIENT',
 'device_availability=No',
 'other_id_number=',
 'generic_name=INFUSION PUMP',
 'manufacturer_d_name=MEDTRONIC MINIMED',
 'brand_name=PUMP MMT-511LNAL PRDGM INS CL EN US LN',
 'manufacturer_d_country=US',
 'combination_product_flag=N',
 'openfda={device_name=Pump',
 'Infusion',
 'Insulin',
 'medical_specialty_description=General Hospital',
 'device_class=2',
 'regulation_number=880.5725}',
 'device_age_text=DA',
 'udi_di=',
 'device_evaluated_by_manufacturer=R',
 'catalog_number=MMT-511LNAL',
 'implant_flag=',
 'date_removed_flag=}']

In [17]:
device_keys = ['manufacturer_d_address_1', 'manufacturer_d_address_2', 'device_event_key', 'device_sequence_number',
               'manufacturer_d_state', 'manufacturer_d_zip_code', 'manufacturer_d_city', 'lot_number',
               'manufacturer_d_postal_code', 'manufacturer_d_zip_code_ext', 'date_received', 'model_number',
               'device_report_product_code', 'udi_public', 'device_operator', 'device_availability',
               'other_id_number', 'generic_name', 'manufacturer_d_name', 'brand_name', 'manufacturer_d_country',
               'combination_product_flag', 'openfda', 'device_age_text', 'udi_di',
               'device_evaluated_by_manufacturer', 'catalog_number', 'implant_flag', 'date_removed_flag']
def convert_device_string_with_equal_to_sign_to_dict(device_string):
    out_dict = dict()
    device_string = str(device_string)
    device_string.strip()
    device_string = device_string[1:-1]
    # device_vals = list()
    for idx, _ in enumerate(device_keys):
        key = "device." + device_keys[idx]
        if idx < len(device_keys) - 1:
            search_pattern = device_keys[idx] + '=(.*?)' + device_keys[idx + 1] + '='
            result = re.search(search_pattern, device_string)
            if result.group(1) == ', ':
                # device_vals.append(None)
                out_dict[key] = None
            else:
                out_dict[key] = result.group(1)
                # device_vals.append(result.group(1))
    last_val = device_string.split(device_keys[-1] + '=')[1]
    last_key = "device." + device_keys[-1]
    out_dict[last_key] = last_val
    # device_vals.append(last_val if last_val else None)
    
    
    return out_dict

In [18]:
out_dict1 = convert_device_string_with_equal_to_sign_to_dict(first_row_device)

In [19]:
out_dict1

{'device.manufacturer_d_address_1': '18000 DEVONSHIRE ST., ',
 'device.manufacturer_d_address_2': None,
 'device.device_event_key': None,
 'device.device_sequence_number': '1, ',
 'device.manufacturer_d_state': 'CA, ',
 'device.manufacturer_d_zip_code': '91325, ',
 'device.manufacturer_d_city': 'NORTHRIDGE, ',
 'device.lot_number': None,
 'device.manufacturer_d_postal_code': '91325, ',
 'device.manufacturer_d_zip_code_ext': None,
 'device.date_received': '20100204, ',
 'device.model_number': 'MMT-511LNAL, ',
 'device.device_report_product_code': 'LZG, ',
 'device.udi_public': None,
 'device.device_operator': 'LAY USER/PATIENT, ',
 'device.device_availability': 'No, ',
 'device.other_id_number': None,
 'device.generic_name': 'INFUSION PUMP, ',
 'device.manufacturer_d_name': 'MEDTRONIC MINIMED, ',
 'device.brand_name': 'PUMP MMT-511LNAL PRDGM INS CL EN US LN, ',
 'device.manufacturer_d_country': 'US, ',
 'device.combination_product_flag': 'N, ',
 'device.openfda': '{device_name=Pump, Infusion, Insulin, medical_specialty_description=General Hospital, device_class=2, regulation_number=880.5725}, ',
 'device.device_age_text': 'DA, ',
 'device.udi_di': None,
 'device.device_evaluated_by_manufacturer': 'R, ',
 'device.catalog_number': 'MMT-511LNAL, ',
 'device.implant_flag': None,
 'device.date_removed_flag': ''}

In [20]:
first_row_device

'{manufacturer_d_address_1=18000 DEVONSHIRE ST., manufacturer_d_address_2=, device_event_key=, device_sequence_number=1, manufacturer_d_state=CA, manufacturer_d_zip_code=91325, manufacturer_d_city=NORTHRIDGE, lot_number=, manufacturer_d_postal_code=91325, manufacturer_d_zip_code_ext=, date_received=20100204, model_number=MMT-511LNAL, device_report_product_code=LZG, udi_public=, device_operator=LAY USER/PATIENT, device_availability=No, other_id_number=, generic_name=INFUSION PUMP, manufacturer_d_name=MEDTRONIC MINIMED, brand_name=PUMP MMT-511LNAL PRDGM INS CL EN US LN, manufacturer_d_country=US, combination_product_flag=N, openfda={device_name=Pump, Infusion, Insulin, medical_specialty_description=General Hospital, device_class=2, regulation_number=880.5725}, device_age_text=DA, udi_di=, device_evaluated_by_manufacturer=R, catalog_number=MMT-511LNAL, implant_flag=, date_removed_flag=}'

In [23]:
import re
# for idx, _ in enumerate(device_keys):
#    subsplit_text = first_row_device[1:-1].split(device_keys[idx])
    # print(first_row_device[1:-1].split(device_keys[idx]))
    
# first_row_device[1:-1].split(device_keys[0] + "=")
# re.split(device_keys[0], first_row_device[1:-1])
search_pattern = device_keys[0] + '=(.*?)' + device_keys[1] + '='
search_pattern
result = re.search(search_pattern, first_row_device[1:-1])
result.group(1)

'18000 DEVONSHIRE ST., '

In [152]:
device_vals = list()
for idx, _ in enumerate(device_keys):
    if idx < len(device_keys) - 1:
        search_pattern = device_keys[idx] + '=(.*?)' + device_keys[idx + 1] + '='
        print(search_pattern)
        result = re.search(search_pattern, first_row_device[1:-1])
        print(result.group(1))
        if result.group(1) == ', ':
            device_vals.append(None)
        else:
            device_vals.append(result.group(1))
last_val = first_row_device[1:-1].split(device_keys[-1] + '=')[1]
device_vals.append(last_val if last_val else None)

manufacturer_d_address_1=(.*?)manufacturer_d_address_2=
18000 DEVONSHIRE ST.,
manufacturer_d_address_2=(.*?)device_event_key=
,
device_event_key=(.*?)device_sequence_number=
,
device_sequence_number=(.*?)manufacturer_d_state=
1,
manufacturer_d_state=(.*?)manufacturer_d_zip_code=
CA,
manufacturer_d_zip_code=(.*?)manufacturer_d_city=
91325,
manufacturer_d_city=(.*?)lot_number=
NORTHRIDGE,
lot_number=(.*?)manufacturer_d_postal_code=
,
manufacturer_d_postal_code=(.*?)manufacturer_d_zip_code_ext=
91325,
manufacturer_d_zip_code_ext=(.*?)date_received=
,
date_received=(.*?)model_number=
20100204,
model_number=(.*?)device_report_product_code=
MMT-511LNAL,
device_report_product_code=(.*?)udi_public=
LZG,
udi_public=(.*?)device_operator=
,
device_operator=(.*?)device_availability=
LAY USER/PATIENT,
device_availability=(.*?)other_id_number=
No,
other_id_number=(.*?)generic_name=
,
generic_name=(.*?)manufacturer_d_name=
INFUSION PUMP,
manufacturer_d_name=(.*?)brand_name=
MEDTRONIC MINIMED,
brand_name=(.*?)manufacturer_d_country=
PUMP MMT-511LNAL PRDGM INS CL EN US LN,
manufacturer_d_country=(.*?)combination_product_flag=
US,
combination_product_flag=(.*?)openfda=
N,
openfda=(.*?)device_age_text=
{device_name=Pump, Infusion, Insulin, medical_specialty_description=General Hospital, device_class=2, regulation_number=880.5725},
device_age_text=(.*?)udi_di=
DA,
udi_di=(.*?)device_evaluated_by_manufacturer=
,
device_evaluated_by_manufacturer=(.*?)catalog_number=
R,
catalog_number=(.*?)implant_flag=
MMT-511LNAL,
implant_flag=(.*?)date_removed_flag=
,

In [153]:
device_keys, device_vals

(['manufacturer_d_address_1',
  'manufacturer_d_address_2',
  'device_event_key',
  'device_sequence_number',
  'manufacturer_d_state',
  'manufacturer_d_zip_code',
  'manufacturer_d_city',
  'lot_number',
  'manufacturer_d_postal_code',
  'manufacturer_d_zip_code_ext',
  'date_received',
  'model_number',
  'device_report_product_code',
  'udi_public',
  'device_operator',
  'device_availability',
  'other_id_number',
  'generic_name',
  'manufacturer_d_name',
  'brand_name',
  'manufacturer_d_country',
  'combination_product_flag',
  'openfda',
  'device_age_text',
  'udi_di',
  'device_evaluated_by_manufacturer',
  'catalog_number',
  'implant_flag',
  'date_removed_flag'],
 ['18000 DEVONSHIRE ST., ',
  None,
  None,
  '1, ',
  'CA, ',
  '91325, ',
  'NORTHRIDGE, ',
  None,
  '91325, ',
  None,
  '20100204, ',
  'MMT-511LNAL, ',
  'LZG, ',
  None,
  'LAY USER/PATIENT, ',
  'No, ',
  None,
  'INFUSION PUMP, ',
  'MEDTRONIC MINIMED, ',
  'PUMP MMT-511LNAL PRDGM INS CL EN US LN, ',
  'US, ',
  'N, ',
  '{device_name=Pump, Infusion, Insulin, medical_specialty_description=General Hospital, device_class=2, regulation_number=880.5725}, ',
  'DA, ',
  None,
  'R, ',
  'MMT-511LNAL, ',
  None,
  None])

In [154]:
len(device_keys), len(device_vals)

(29, 29)

In [166]:
first_row_device_dict = convert_device_string_with_equal_to_sign_to_dict(first_row_device)

In [167]:
first_row_device_dict

{'device.manufacturer_d_address_1': '18000 DEVONSHIRE ST., ',
 'device.manufacturer_d_address_2': None,
 'device.device_event_key': None,
 'device.device_sequence_number': '1, ',
 'device.manufacturer_d_state': 'CA, ',
 'device.manufacturer_d_zip_code': '91325, ',
 'device.manufacturer_d_city': 'NORTHRIDGE, ',
 'device.lot_number': None,
 'device.manufacturer_d_postal_code': '91325, ',
 'device.manufacturer_d_zip_code_ext': None,
 'device.date_received': '20100204, ',
 'device.model_number': 'MMT-511LNAL, ',
 'device.device_report_product_code': 'LZG, ',
 'device.udi_public': None,
 'device.device_operator': 'LAY USER/PATIENT, ',
 'device.device_availability': 'No, ',
 'device.other_id_number': None,
 'device.generic_name': 'INFUSION PUMP, ',
 'device.manufacturer_d_name': 'MEDTRONIC MINIMED, ',
 'device.brand_name': 'PUMP MMT-511LNAL PRDGM INS CL EN US LN, ',
 'device.manufacturer_d_country': 'US, ',
 'device.combination_product_flag': 'N, ',
 'device.openfda': '{device_name=Pump, Infusion, Insulin, medical_specialty_description=General Hospital, device_class=2, regulation_number=880.5725}, ',
 'device.device_age_text': 'DA, ',
 'device.udi_di': None,
 'device.device_evaluated_by_manufacturer': 'R, ',
 'device.catalog_number': 'MMT-511LNAL, ',
 'device.implant_flag': None,
 'device.date_removed_flag': ''}

In [168]:
df['device'] = df['device'].apply(lambda dev: convert_string_with_equal_to_sign_to_dict(dev, "device"))
# device_parsed_df = pd.DataFrame.from_dict(df["device"].map(lambda d : d.values.tolist())

In [169]:
df['device']

0       {'device.manufacturer_d_address_1': '18000 DEV...
1       {'device.manufacturer_d_address_1': 'CEIBA NOR...
2       {'device.manufacturer_d_address_1': '200 LAWRE...
3       {'device.manufacturer_d_address_1': 'CALL BOX ...
4       {'device.manufacturer_d_address_1': '18000 DEV...
                              ...
3089    {'device.manufacturer_d_address_1': 'CEIBA NOR...
3090    {'device.manufacturer_d_address_1': 'CEIBA NOR...
3091    {'device.manufacturer_d_address_1': '', 'devic...
3092    {'device.manufacturer_d_address_1': '', 'devic...
3093    {'device.manufacturer_d_address_1': '', 'devic...
Name: device, Length: 3094, dtype: object

In [234]:
first_row_mdr_text

'{mdr_text_key=21989596, text_type_code=Additional Manufacturer Narrative, patient_sequence_number=1, text=CURRENTLY, IT IS UNK WHETHER OR NOT THE DEVICE MAY HAVE CAUSED OR CONTRIBUTED TO THE EVENT AS NO PRODUCT HAS BEEN RETURNED. NO CONCLUSION CAN BE DRAWN AT THIS TIME. WE THEREFORE CONSIDER THIS REPORT COMPLETE TO THE BEST OF OUR KNOWLEDGE.}'

In [175]:
mdr_text_keys = ['mdr_text_key', 'text_type_code', 'patient_sequence_number', 'text']
def convert_mdr_text_string_with_equal_to_sign_to_dict(mdr_text_string):
    out_dict = dict()
    mdr_text_string = str(mdr_text_string)
    mdr_text_string.strip()
    mdr_text_string = mdr_text_string[1:-1]
    # device_vals = list()
    for idx, _ in enumerate(mdr_text_keys):
        key = "mdr_text." + mdr_text_keys[idx]
        if idx < len(mdr_text_keys) - 1:
            search_pattern = mdr_text_keys[idx] + '=(.*?)' + mdr_text_keys[idx + 1] + '='
            result = re.search(search_pattern, mdr_text_string)
            if result.group(1) == ', ':
                # device_vals.append(None)
                out_dict[key] = None
            else:
                out_dict[key] = result.group(1)
                # device_vals.append(result.group(1))
    last_val = mdr_text_string.split(mdr_text_keys[-1] + '=')[1]
    last_key = "mdr_text." + mdr_text_keys[-1]
    out_dict[last_key] = last_val
    # device_vals.append(last_val if last_val else None)
    
    
    return out_dict

In [176]:
out_dict2 = convert_mdr_text_string_with_equal_to_sign_to_dict(first_row_mdr_text)

In [177]:
out_dict2

{'mdr_text.mdr_text_key': '21989596, ',
 'mdr_text.text_type_code': 'Additional Manufacturer Narrative, ',
 'mdr_text.patient_sequence_number': '1, ',
 'mdr_text.text': 'CURRENTLY, IT IS UNK WHETHER OR NOT THE DEVICE MAY HAVE CAUSED OR CONTRIBUTED TO THE EVENT AS NO PRODUCT HAS BEEN RETURNED. NO CONCLUSION CAN BE DRAWN AT THIS TIME. WE THEREFORE CONSIDER THIS REPORT COMPLETE TO THE BEST OF OUR KNOWLEDGE.'}

In [311]:
'{' + ''.join(key + '=, ' for key in device_keys) + '}'

'{manufacturer_d_address_1=, manufacturer_d_address_2=, device_event_key=, device_sequence_number=, manufacturer_d_state=, manufacturer_d_zip_code=, manufacturer_d_city=, lot_number=, manufacturer_d_postal_code=, manufacturer_d_zip_code_ext=, date_received=, model_number=, device_report_product_code=, udi_public=, device_operator=, device_availability=, other_id_number=, generic_name=, manufacturer_d_name=, brand_name=, manufacturer_d_country=, combination_product_flag=, openfda=, device_age_text=, udi_di=, device_evaluated_by_manufacturer=, catalog_number=, implant_flag=, date_removed_flag=, }'

In [312]:
'{' + ''.join(key + '=, ' for key in mdr_text_keys) + '}'

'{mdr_text_key=, text_type_code=, patient_sequence_number=, text=, }'

In [338]:
device_keys = ['manufacturer_d_address_1', 'manufacturer_d_address_2', 'device_event_key', 'device_sequence_number',
               'manufacturer_d_state', 'manufacturer_d_zip_code', 'manufacturer_d_city', 'lot_number',
               'manufacturer_d_postal_code', 'manufacturer_d_zip_code_ext', 'date_received', 'model_number',
               'device_report_product_code', 'udi_public', 'device_operator', 'device_availability',
               'other_id_number', 'generic_name', 'manufacturer_d_name', 'brand_name', 'manufacturer_d_country',
               'combination_product_flag', 'openfda', 'device_age_text', 'udi_di',
               'device_evaluated_by_manufacturer', 'catalog_number', 'implant_flag', 'date_removed_flag']
mdr_text_keys = ['mdr_text_key', 'text_type_code', 'patient_sequence_number', 'text']
df['device'].fillna('{' + ''.join(key + '=, ' for key in device_keys) + '}', inplace=True)
df['mdr_text'].fillna('{' + ''.join(key + '=, ' for key in mdr_text_keys) + '}', inplace=True)
def convert_string_with_equal_to_sign_to_dict(in_string, column_name):
    out_dict = dict()
    in_string = str(in_string)
    in_string.strip()
    in_string = in_string[1:-1]
    if column_name == 'device':
        keys = device_keys
    else:
        keys = mdr_text_keys
    for idx, _ in enumerate(keys):
        key = column_name + "." + keys[idx]
        if idx < len(keys) - 1:
            search_pattern = keys[idx] + '=(.*?)' + keys[idx + 1] + '='
            result = re.search(search_pattern, in_string)
            if result:
                if result.group(1) == ', ':
                    out_dict[key] = None
                else:
                    out_dict[key] = result.group(1)
            else:
                out_dict[key] = None
    try:
        last_val = in_string.split(keys[-1] + '=')[1]
        if last_val == ', ':
            last_val = None
    except Exception as err:
        print(f"the error is: {repr(err)}")
        print(f"the in string is: {in_string}")
        raise Exception
    last_key = column_name + "." + keys[-1]
    out_dict[last_key] = last_val
    
    return out_dict

In [339]:
out_dict1 = convert_string_with_equal_to_sign_to_dict(first_row_device, "device")

In [340]:
out_dict2 = convert_string_with_equal_to_sign_to_dict(first_row_mdr_text, "mdr_text")

In [341]:
eight_hundred_sixty_fourth_mdr_text = df['mdr_text'][864]

In [342]:
eight_hundred_sixty_fourth_mdr_text

'{mdr_text_key=, text_type_code=, patient_sequence_number=, text=, }'

In [343]:
type(eight_hundred_sixty__fourth_mdr_text)

float

In [344]:
out_dict864 = convert_string_with_equal_to_sign_to_dict(eight_hundred_sixty_fourth_mdr_text, "mdr_text")

In [345]:
out_dict864

{'mdr_text.mdr_text_key': None,
 'mdr_text.text_type_code': None,
 'mdr_text.patient_sequence_number': None,
 'mdr_text.text': None}

In [346]:
out_dict1

{'device.manufacturer_d_address_1': '18000 DEVONSHIRE ST., ',
 'device.manufacturer_d_address_2': None,
 'device.device_event_key': None,
 'device.device_sequence_number': '1, ',
 'device.manufacturer_d_state': 'CA, ',
 'device.manufacturer_d_zip_code': '91325, ',
 'device.manufacturer_d_city': 'NORTHRIDGE, ',
 'device.lot_number': None,
 'device.manufacturer_d_postal_code': '91325, ',
 'device.manufacturer_d_zip_code_ext': None,
 'device.date_received': '20100204, ',
 'device.model_number': 'MMT-511LNAL, ',
 'device.device_report_product_code': 'LZG, ',
 'device.udi_public': None,
 'device.device_operator': 'LAY USER/PATIENT, ',
 'device.device_availability': 'No, ',
 'device.other_id_number': None,
 'device.generic_name': 'INFUSION PUMP, ',
 'device.manufacturer_d_name': 'MEDTRONIC MINIMED, ',
 'device.brand_name': 'PUMP MMT-511LNAL PRDGM INS CL EN US LN, ',
 'device.manufacturer_d_country': 'US, ',
 'device.combination_product_flag': 'N, ',
 'device.openfda': '{device_name=Pump, Infusion, Insulin, medical_specialty_description=General Hospital, device_class=2, regulation_number=880.5725}, ',
 'device.device_age_text': 'DA, ',
 'device.udi_di': None,
 'device.device_evaluated_by_manufacturer': 'R, ',
 'device.catalog_number': 'MMT-511LNAL, ',
 'device.implant_flag': None,
 'device.date_removed_flag': ''}

In [347]:
out_dict2

{'mdr_text.mdr_text_key': '21989596, ',
 'mdr_text.text_type_code': 'Additional Manufacturer Narrative, ',
 'mdr_text.patient_sequence_number': '1, ',
 'mdr_text.text': 'CURRENTLY, IT IS UNK WHETHER OR NOT THE DEVICE MAY HAVE CAUSED OR CONTRIBUTED TO THE EVENT AS NO PRODUCT HAS BEEN RETURNED. NO CONCLUSION CAN BE DRAWN AT THIS TIME. WE THEREFORE CONSIDER THIS REPORT COMPLETE TO THE BEST OF OUR KNOWLEDGE.'}

In [348]:
df['device'] = df['device'].apply(lambda dev: convert_string_with_equal_to_sign_to_dict(dev, "device"))
df['mdr_text'] = df['mdr_text'].apply(lambda mdr: convert_string_with_equal_to_sign_to_dict(mdr, "mdr_text"))

In [349]:
df['device']

0       {'device.manufacturer_d_address_1': '18000 DEV...
1       {'device.manufacturer_d_address_1': 'CEIBA NOR...
2       {'device.manufacturer_d_address_1': '200 LAWRE...
3       {'device.manufacturer_d_address_1': 'CALL BOX ...
4       {'device.manufacturer_d_address_1': '18000 DEV...
                              ...
3089    {'device.manufacturer_d_address_1': 'CEIBA NOR...
3090    {'device.manufacturer_d_address_1': 'CEIBA NOR...
3091    {'device.manufacturer_d_address_1': None, 'dev...
3092    {'device.manufacturer_d_address_1': None, 'dev...
3093    {'device.manufacturer_d_address_1': None, 'dev...
Name: device, Length: 3094, dtype: object

In [350]:
df['mdr_text']

0       {'mdr_text.mdr_text_key': '21989596, ', 'mdr_t...
1       {'mdr_text.mdr_text_key': '3151704, ', 'mdr_te...
2       {'mdr_text.mdr_text_key': '18178260, ', 'mdr_t...
3       {'mdr_text.mdr_text_key': '21829400, ', 'mdr_t...
4       {'mdr_text.mdr_text_key': '3756111, ', 'mdr_te...
                              ...
3089    {'mdr_text.mdr_text_key': '217286873, ', 'mdr_...
3090    {'mdr_text.mdr_text_key': '140732662, ', 'mdr_...
3091    {'mdr_text.mdr_text_key': '209451174, ', 'mdr_...
3092    {'mdr_text.mdr_text_key': '64067345, ', 'mdr_t...
3093    {'mdr_text.mdr_text_key': '65097409, ', 'mdr_t...
Name: mdr_text, Length: 3094, dtype: object

In [351]:
device_parsed_df = pd.DataFrame.from_dict(df["device"].values.tolist())
mdr_text_parsed_df = pd.DataFrame.from_dict(df["mdr_text"].values.tolist())

In [352]:
device_parsed_df

,device.manufacturer_d_address_1,device.manufacturer_d_address_2,device.device_event_key,device.device_sequence_number,device.manufacturer_d_state,device.manufacturer_d_zip_code,device.manufacturer_d_city,device.lot_number,device.manufacturer_d_postal_code,device.manufacturer_d_zip_code_ext,...,device.brand_name,device.manufacturer_d_country,device.combination_product_flag,device.openfda,device.device_age_text,device.udi_di,device.device_evaluated_by_manufacturer,device.catalog_number,device.implant_flag,device.date_removed_flag
0,"18000 DEVONSHIRE ST.,",None,None,"1,","CA,","91325,","NORTHRIDGE,",None,"91325,",None,...,"PUMP MMT-511LNAL PRDGM INS CL EN US LN,","US,","N,","{device_name=Pump, Infusion, Insulin, medical_...","DA,",None,"R,","MMT-511LNAL,",None,
1,"CEIBA NORTE IND. PARK #50,","ROAD 31 KM 24.4,",None,"1,","PR,","00777,","JUNCOS,",None,"00777 3869,","386,",...,"PARADIGM REAL-TIME INSULIN INFUSION PUMP,","US,","N,","{device_name=Pump, Infusion, Insulin, To Be Us...",None,None,"R,","MMT-522CAS,",None,
2,"200 LAWRENCE DR,",None,None,"1,","PA,","19380,","WEST CHESTER,",None,"19380 3428,","342,",...,"ANIMAS INSULIN INFUSION PUMP,","US,","N,","{device_name=Pump, Infusion, Insulin, medical_...","DA,",None,"R,",None,None,
3,"CALL BOX 4070, RD31, KM24, HM4,","CEIBA NORTE INDUSTRIAL PARK,",None,"1,","PR,","00777,","JUNCOS,",None,"00777 4070,","407,",...,"PUMP MMT-722NAP PRDGM INS V2.2 PL EN,","US,","N,","{device_name=Pump, Infusion, Insulin, medical_...","DA,",None,"R,","MMT-722NAP,",None,
4,"18000 DEVONSHIRE STREET,",None,None,"1,","CA,","91325,","NORTHRIDGE,",None,"91325,",None,...,"PARADIGM INSULIN INFUSION PUMP,","US,","N,","{device_name=Pump, Infusion, Insulin, medical_...",None,None,"R,","MMT-712NAS,",None,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3089,"CEIBA NORTE IND. PARK #50 ROAD,",None,None,"1,",None,"00777,","JUNCOS,",None,"00777-3869,","-386,",...,"RESERVOIR 3ML MMT-332A,","*,","N,","{device_name=Pump, Infusion, medical_specialty...",None,None,"*,","MMT-332A,",None,
3090,"CEIBA NORTE IND. PARK #50 ROAD,",None,None,"1,",None,"00777,","JUNCOS,",None,"00777-3869,","-386,",...,"RESERVOIR 3ML MMT-332A,",None,"N,","{device_name=Pump, Infusion, medical_specialty...",None,None,"*,","MMT-332A,",None,
3091,None,None,None,"1,","IL,",None,"DEERFIELD,","NA,",None,None,...,"SPECTRUM INFUSION PUMP,",None,"Y,","{device_name=Pump, Infusion, medical_specialty...","DA,","00085412498683,","R,","35700BAX2,",None,
3092,None,None,None,"1,",None,None,None,None,None,None,...,"PARADIGM REAL-TIME REVEL INSULIN INFUSION PUMP,",None,"N,","{device_name=Pump, Infusion, Insulin, To Be Us...",None,None,"R,","MMT-723RNAS,",None,
3093,None,None,None,"1,",None,None,None,None,None,None,...,"INSULIN INFUSION PUMP,",None,"N,","{device_name=Pump, Infusion, Insulin, To Be Us...",None,None,"R,","MMT-XXX,",None,

In [353]:
mdr_text_parsed_df

,mdr_text.mdr_text_key,mdr_text.text_type_code,mdr_text.patient_sequence_number,mdr_text.text
0,"21989596,","Additional Manufacturer Narrative,","1,","CURRENTLY, IT IS UNK WHETHER OR NOT THE DEVICE..."
1,"3151704,","Description of Event or Problem,","1,","IT WAS REPORTED THAT THE CUSTOMER PASSED AWAY,..."
2,"18178260,","Description of Event or Problem,","1,",IT WAS REPORTED THAT THE PATIENT DIED ON (B)(6...
3,"21829400,","Additional Manufacturer Narrative,","1,","CURRENTLY, IT IS UNKNOWN WHETHER OR NOT THE DE..."
4,"3756111,","Description of Event or Problem,","1,",IT WAS REPORTED THAT THE CUSTOMER PASSED AWAY....
...,...,...,...,...
3089,"217286873,","Additional Manufacturer Narrative,","1,",(B)(4). CURRENTLY IT IS UNKNOWN WHETHER OR NOT...
3090,"140732662,","Additional Manufacturer Narrative,","1,",CURRENTLY IT IS UNKNOWN WHETHER OR NOT THE DEV...
3091,"209451174,","Additional Manufacturer Narrative,","1,",SHOULD ADDITIONAL RELEVANT INFORMATION BECOME ...
3092,"64067345,","Additional Manufacturer Narrative,","1,","CURRENTLY, IT IS UNKNOWN WHETHER OR NOT THE DE..."
3093,"65097409,","Additional Manufacturer Narrative,","1,",CURRENTLY IT IS UNKNOWN WHETHER OR NOT THE DEV...

In [356]:
df = pd.merge(df, device_parsed_df, left_index=True, right_index=True)

In [357]:
df.head(5)

,manufacturer_contact_zip_ext,manufacturer_g1_address_2,manufacturer_link_flag,event_type,manufacturer_contact_pcity,report_number,type_of_report,date_received,manufacturer_address_2,date_of_event,...,device.brand_name,device.manufacturer_d_country,device.combination_product_flag,device.openfda,device.device_age_text,device.udi_di,device.device_evaluated_by_manufacturer,device.catalog_number,device.implant_flag,device.date_removed_flag
0,1219,NaN,Y,Death,81857643,2032227-2010-80235,Initial submission,20100204,NaN,20091015.0,...,"PUMP MMT-511LNAL PRDGM INS CL EN US LN,","US,","N,","{device_name=Pump, Infusion, Insulin, medical_...","DA,",None,"R,","MMT-511LNAL,",None,
1,1219,ROAD 31 KM 24.4,Y,Death,81857643,3004209178-2013-90526,Initial submission,20130123,NaN,20120822.0,...,"PARADIGM REAL-TIME INSULIN INFUSION PUMP,","US,","N,","{device_name=Pump, Infusion, Insulin, To Be Us...",None,None,"R,","MMT-522CAS,",None,
2,3428,NaN,Y,Death,40895647,2531779-2011-04263,Initial submission,20110618,NaN,20110428.0,...,"ANIMAS INSULIN INFUSION PUMP,","US,","N,","{device_name=Pump, Infusion, Insulin, medical_...","DA,",None,"R,",None,None,
3,1219,CEIBA NORTE INDUSTRIAL PARK,Y,Death,81857643,3004209178-2010-80078,Initial submission,20100119,NaN,20090425.0,...,"PUMP MMT-722NAP PRDGM INS V2.2 PL EN,","US,","N,","{device_name=Pump, Infusion, Insulin, medical_...","DA,",None,"R,","MMT-722NAP,",None,
4,1219,NaN,Y,Death,81857643,2032227-2013-03519,Initial submission,20130810,NaN,20080901.0,...,"PARADIGM INSULIN INFUSION PUMP,","US,","N,","{device_name=Pump, Infusion, Insulin, medical_...",None,None,"R,","MMT-712NAS,",None,

In [358]:
df = pd.merge(df, mdr_text_parsed_df, left_index=True, right_index=True)

In [359]:
df

,manufacturer_contact_zip_ext,manufacturer_g1_address_2,manufacturer_link_flag,event_type,manufacturer_contact_pcity,report_number,type_of_report,date_received,manufacturer_address_2,date_of_event,...,device.device_age_text,device.udi_di,device.device_evaluated_by_manufacturer,device.catalog_number,device.implant_flag,device.date_removed_flag,mdr_text.mdr_text_key,mdr_text.text_type_code,mdr_text.patient_sequence_number,mdr_text.text
0,1219,NaN,Y,Death,81857643,2032227-2010-80235,Initial submission,20100204,NaN,20091015.0,...,"DA,",None,"R,","MMT-511LNAL,",None,,"21989596,","Additional Manufacturer Narrative,","1,","CURRENTLY, IT IS UNK WHETHER OR NOT THE DEVICE..."
1,1219,ROAD 31 KM 24.4,Y,Death,81857643,3004209178-2013-90526,Initial submission,20130123,NaN,20120822.0,...,None,None,"R,","MMT-522CAS,",None,,"3151704,","Description of Event or Problem,","1,","IT WAS REPORTED THAT THE CUSTOMER PASSED AWAY,..."
2,3428,NaN,Y,Death,40895647,2531779-2011-04263,Initial submission,20110618,NaN,20110428.0,...,"DA,",None,"R,",None,None,,"18178260,","Description of Event or Problem,","1,",IT WAS REPORTED THAT THE PATIENT DIED ON (B)(6...
3,1219,CEIBA NORTE INDUSTRIAL PARK,Y,Death,81857643,3004209178-2010-80078,Initial submission,20100119,NaN,20090425.0,...,"DA,",None,"R,","MMT-722NAP,",None,,"21829400,","Additional Manufacturer Narrative,","1,","CURRENTLY, IT IS UNKNOWN WHETHER OR NOT THE DE..."
4,1219,NaN,Y,Death,81857643,2032227-2013-03519,Initial submission,20130810,NaN,20080901.0,...,None,None,"R,","MMT-712NAS,",None,,"3756111,","Description of Event or Problem,","1,",IT WAS REPORTED THAT THE CUSTOMER PASSED AWAY....
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3089,'-386,NaN,Y,Death,81854648,2032227-2020-207591,Initial submission,20201119,NaN,20190731.0,...,None,None,"*,","MMT-332A,",None,,"217286873,","Additional Manufacturer Narrative,","1,",(B)(4). CURRENTLY IT IS UNKNOWN WHETHER OR NOT...
3090,'-386,NaN,Y,Death,81854648,3004209178-2019-76535,Initial submission,20190403,NaN,20170809.0,...,None,None,"*,","MMT-332A,",None,,"140732662,","Additional Manufacturer Narrative,","1,",CURRENTLY IT IS UNKNOWN WHETHER OR NOT THE DEV...
3091,NaN,NaN,Y,Death,22427020,1314492-2020-03254,Initial submission,20201001,NaN,20200827.0,...,"DA,","00085412498683,","R,","35700BAX2,",None,,"209451174,","Additional Manufacturer Narrative,","1,",SHOULD ADDITIONAL RELEVANT INFORMATION BECOME ...
3092,1219,NaN,Y,Death,81857648,2032227-2017-00191,Initial submission,20170106,NaN,20161226.0,...,None,None,"R,","MMT-723RNAS,",None,,"64067345,","Additional Manufacturer Narrative,","1,","CURRENTLY, IT IS UNKNOWN WHETHER OR NOT THE DE..."
3093,1219,NaN,Y,Death,81857648,2032227-2017-01028,Initial submission,20170118,NaN,20160809.0,...,None,None,"R,","MMT-XXX,",None,,"65097409,","Additional Manufacturer Narrative,","1,",CURRENTLY IT IS UNKNOWN WHETHER OR NOT THE DEV...

In [360]:
df['device']

0       {'device.manufacturer_d_address_1': '18000 DEV...
1       {'device.manufacturer_d_address_1': 'CEIBA NOR...
2       {'device.manufacturer_d_address_1': '200 LAWRE...
3       {'device.manufacturer_d_address_1': 'CALL BOX ...
4       {'device.manufacturer_d_address_1': '18000 DEV...
                              ...
3089    {'device.manufacturer_d_address_1': 'CEIBA NOR...
3090    {'device.manufacturer_d_address_1': 'CEIBA NOR...
3091    {'device.manufacturer_d_address_1': None, 'dev...
3092    {'device.manufacturer_d_address_1': None, 'dev...
3093    {'device.manufacturer_d_address_1': None, 'dev...
Name: device, Length: 3094, dtype: object

In [361]:
df['device.manufacturer_d_name']

0                              MEDTRONIC MINIMED,
1           MEDTRONIC PUERTO RICO OPERATIONS CO.,
2                             ANIMAS CORPORATION,
3       MEDTRONIC PUERTO RICO OPERATIONS MED-REL,
4                              MEDTRONIC MINIMED,
                           ...
3089        MEDTRONIC PUERTO RICO OPERATIONS CO.,
3090        MEDTRONIC PUERTO RICO OPERATIONS CO.,
3091               BAXTER HEALTHCARE CORPORATION,
3092                                          None
3093                                          None
Name: device.manufacturer_d_name, Length: 3094, dtype: object

In [362]:
df['mdr_text.mdr_text_key']

0        21989596,
1         3151704,
2        18178260,
3        21829400,
4         3756111,
           ...
3089    217286873,
3090    140732662,
3091    209451174,
3092     64067345,
3093     65097409,
Name: mdr_text.mdr_text_key, Length: 3094, dtype: object

In [363]:
df.to_csv('insulin_infusion_pump_death_device_mdr_text_columns_separated.csv', index=False)